//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Items()
        {
            this.Returns = new HashSet<Returns>();
        }
    
        public string Item_ID { get; set; }
        public string Order_ID { get; set; }
        public string Stock_ID { get; set; }
        public string isbn { get; set; }
        public string Supplier_ID { get; set; }
        public string Retail_Price { get; set; }
        public string Qty_sold { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Stocks Stocks { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
