//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocks()
        {
            this.Order_Items = new HashSet<Order_Items>();
            this.Returns = new HashSet<Returns>();
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public string STOCK_ID { get; set; }
        public string isbn { get; set; }
        public string Author_name { get; set; }
        public string Title_name { get; set; }
        public string Publisher_name { get; set; }
        public string Published_year { get; set; }
        public string Supplier_ID { get; set; }
        public string Retail_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
