//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public string Supplier_ID { get; set; }
        public string Stock_ID { get; set; }
        public string Supplier_name { get; set; }
        public string Supplier_City { get; set; }
        public string Supplier_Street { get; set; }
        public string Supplier_PCode { get; set; }
        public string Supplier_email { get; set; }
        public string Supplier_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
